<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title">Listado</h3>
	  </div>
	  <div class="panel-body">
				<table class="table table-striped table-bordered table-hover" id="dataTablesAdvanced">
					<thead>
						<tr>
							<th>Año</th>
							<th>Descripcion</th>
							<th>Actual</th>
							<th class="text-center no-sort" >Acción</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->datos as $key => $dato) { ?>
							<tr>
								<td><?php echo $dato->getAno(); ?></td>
								<td><?php echo $dato->getDescripcion(); ?></td>
								<td><?php echo $dato->getActual()?'SI':'NO'; ?></td>
								<td class="text-center">
									<a title="Actualizar" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>actualizar/<?php echo $dato->getId(); ?>/"><i class="fa fa-pencil-square-o"></i></a>
								</td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
				<a href="<?php echo BASE_URL.$this->_presentRequest->getControlador()."/agregar/" ?>" class="btn btn-primary">Agregar</a>
	  </div>
</div>