<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title"><?php echo ucwords(strtolower($this->_presentRequest->getMetodo())); ?></h3>
	  </div>
	  <div class="panel-body">

	    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
			
			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Año: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="ano" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getAno();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Descripcion: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<textarea class="form-control required" name="descripcion"><?php if(isset($this->dato)){ echo $this->dato->getDescripcion();} ?></textarea>
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Estado: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<div class="btn-group" data-toggle="buttons">
						<label class="btn btn-primary <?php if(isset($this->dato) && $this->dato->getActual()){ echo 'active';} ?>">
							<input type="radio" name="estado" value="1" autocomplete="off" <?php if(isset($this->dato) && $this->dato->getActual()){ echo 'checked';}else if(!isset($this->dato)){ echo 'checked'; } ?>> SI
						</label>
						<label class="btn btn-primary <?php if(isset($this->dato) && !$this->dato->getActual()){ echo 'active';}else if(!isset($this->dato)){ echo 'active'; } ?>">
							<input type="radio" name="estado" value="0" autocomplete="off" <?php if(isset($this->dato) && !$this->dato->getActual()){ echo 'checked';} ?>> NO 
						</label>
					</div>
				</div>
			</div>

			<p class="text-right comentario">
				Los campos marcados con <span class="span">*</span> son obligatorios.
			</p>

			<button type="submit" class="btn btn-primary" ><?php echo ucwords($this->_presentRequest->getMetodo()); ?> </button> 
			<a class="btn btn-primary" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>">Listado</a>

		</form>

	  </div>
</div>

