    <div class="col-xs-12 col-sm-8 col-md-8" id="panelHome">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Sistema de informaci&oacute;n de administraci&oacute;n acad&eacute;mica</h3>
            </div>
            <div class="panel-body">
                <p>
                    El banco de programas y proyectos de inversi&oacute;n municipal es un instrumento din&Aacute;mico de la planeaci&oacute;n que registra los programas y los proyectos viables t&eacute;cnica, ambiental, socioecon&oacute;mica y legalmente susceptibles de ser financiados con recursos p&uacute;blicos en el territorio municipal.
                    </p>
                    <p> 

                    El sistema de informaci&oacute;n de administraci&oacute;n  del banco de programas y proyectos de inversió&oacute;n municipal es una herramienta que tiene como prop&oacute;sito facilitar la sistematizaci&oacute;n del proceso de registro y control de la informaci&oacute;n de estos proyectos, generaci&oacute;n de c&oacute;digo BPPIM, registro de asignaci&oacute;n y demas procesos del banco.

                </p>
            </div>
        </div>
    </div>
    
    <?php 
        if (!Session::get('autenticado')) {
    ?>
    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Iniciar sesi&oacute;n</h3>
            </div>
            <div class="panel-body">
                
                <form role="form" action="<?php echo BASE_URL; ?>login/" method="post">
                    
                    <input type="hidden" name="enviar" value="1" />
                    
                    <div class="form-group">
                        <input type="text" name="usuario" class="form-control" placeholder="Nombre de usuario" value="<?php if (isset($_POST["usuario"])) echo $_POST["usuario"]; ?>">
                    </div>
                    
                    <div class="form-group">
                        <input type="password" name="pass" class="form-control" placeholder="Contrase&ntilde;a">
                    </div>
                    
                   <!-- <div class="checkbox" style="margin: 1.1em 0;">
                        <label>
                            <input type="checkbox" value="recordarme" > Recordarme
                        </label>
                    </div>-->
                    
                    <input type="submit" class="btn btn-success btn-block" value="Iniciar sesi&oacute;n" />
                    
                </form>
            </div>
        </div>
    </div>
    <?php
        }
        else
        {?>
        <script>
            redimensionarHome();
        </script>
     <?php     
        }
    ?>
</div>