    <div class="col-xs-12 col-sm-8 col-md-8" id="panelHome">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Sistema de Gestion Proyectos Regionales</h3>
            </div>
            <div class="panel-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu imperdiet risus. Pellentesque enim ex, placerat congue tortor sed, accumsan scelerisque erat. Mauris vel ultricies ante. Fusce porta egestas tristique. Donec vel vehicula arcu. Nullam ipsum orci, molestie id nulla ac, tempus venenatis orci. Aliquam erat volutpat. Cras nunc eros, dictum ac ex eget, tristique ultricies nulla. Etiam pharetra eget mi id euismod. Nulla in erat ac augue dignissim rhoncus venenatis in elit. Pellentesque nec ultricies nunc. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
                </p>
            </div>
        </div>
    </div>
    
    <?php 
        if (!Session::get('autenticado')) {
    ?>
    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Iniciar sesi&oacute;n</h3>
            </div>
            <div class="panel-body">
                
                <form role="form" action="<?php echo BASE_URL; ?>login/" method="post">
                    
                    <input type="hidden" name="enviar" value="1" />
                    
                    <div class="form-group">
                        <input type="text" name="usuario" class="form-control" placeholder="Nombre de usuario" value="<?php if (isset($_POST["usuario"])) echo $_POST["usuario"]; ?>">
                    </div>
                    
                    <div class="form-group">
                        <input type="password" name="pass" class="form-control" placeholder="Contrase&ntilde;a">
                    </div>
                    
                   <!-- <div class="checkbox" style="margin: 1.1em 0;">
                        <label>
                            <input type="checkbox" value="recordarme" > Recordarme
                        </label>
                    </div>-->
                    
                    <input type="submit" class="btn btn-primary btn-block" value="Iniciar sesi&oacute;n" />
                    
                </form>
            </div>
        </div>
    </div>
    <?php
        }
        else
        {?>
        <script>
            redimensionarHome();
        </script>
     <?php     
        }
    ?>
</div>