<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title"><?php echo ucwords(strtolower($this->_presentRequest->getMetodo())); ?></h3>
	  </div>
	  <div class="panel-body">

	    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">

	    	<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Codigo: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="codigo" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getNombre();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Nombre: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="nombre" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getNombre();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Proponente: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="proponente" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getNombre();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Categoria: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
				<?php $categoria = ''; ?>
				<?php if(isset($this->dato)){ $categoria = $this->dato->getCategoria()->getId(); } ?>
					<?php echo $this->combobox("categoria", "Seleccione...", $this->categorias, $categoria, "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Sector: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
				<?php $sector = ''; ?>
				<?php if(isset($this->dato)){ $sector = $this->dato->getSector()->getId(); } ?>
					<?php echo $this->combobox("sector", "Seleccione...", $this->sectores, $sector, "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Estado: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
				<?php $estado = ''; ?>
				<?php if(isset($this->dato)){ $estado = $this->dato->getEstado()->getId(); } ?>
					<?php echo $this->combobox("estado", "Seleccione...", $this->estados, $estado, "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
				</div>
			</div>

			<p class="text-right comentario">
				Los campos marcados con <span class="span">*</span> son obligatorios.
			</p>

			<button type="submit" class="btn btn-primary" ><?php echo ucwords($this->_presentRequest->getMetodo()); ?> </button> 
			<a class="btn btn-primary" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>">Listado</a>

		</form>

	  </div>
</div>

<?php if(isset($this->dato) && count($this->dato)){ ?>

<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title">Vacunas</h3>
	  </div>
	  <div class="panel-body">

	    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
			<table class="table table-striped table-bordered table-hover" id="dataTablesAdvanced">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Fecha Programada</th>
						<th>Fecha Realizada</th>
						<th>Observacion</th>
						<th class="no-sort" >Accion</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->dato->getVacunaciones() as $key => $dato) { ?>
						<tr>
							<td><?php echo $dato->getVacuna()->getDescripcion(); ?></td>
							<td><?php echo $dato->getFechaProg()->format('d/m/Y'); ?></td>
							<td><?php if($dato->getFechaReal() != null) echo $dato->getFechaReal()->format('d/m/Y'); ?></td>
							<td><?php echo $dato->getObservacion(); ?></td>
							<td class="text-center">
								<a title="Asignar" class="asignarV" vacuna="<?php echo $dato->getId(); ?>" ><i class="fa fa-calendar"></i></a>
								<a title="Eliminar" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>desactivarVacuna/<?php echo $mascota; ?>/<?php echo $dato->getId(); ?>/"><i class="fa fa-times"></i></a>
							</td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
			<a class="btn btn-primary" id="vacuna">Agregar Vacuna</a>
		</form>

	  </div>
</div>

<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title">Servicios</h3>
	  </div>
	  <div class="panel-body">

	    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
			<table class="table table-striped table-bordered table-hover" id="dataTablesAdvanced">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Fecha Programada</th>
						<th>Fecha Realizada</th>
						<th>Observacion</th>
						<th class="no-sort" >Accion</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->dato->getServicios() as $key => $dato) { ?>
						<tr>
							<td><?php echo $dato->getServicio()->getDescripcion(); ?></td>
							<td><?php echo $dato->getFechaProg()->format('d/m/Y'); ?></td>
							<td><?php if($dato->getFechaReal() != null) echo $dato->getFechaReal()->format('d/m/Y'); ?></td>
							<td><?php echo $dato->getObservacion(); ?></td>
							<td class="text-center">
								<a title="Asignar" class="asignarS" servicio="<?php echo $dato->getId(); ?>" ><i class="fa fa-calendar"></i></a>
								<a title="Eliminar" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>desactivarVacuna/<?php echo $mascota; ?>/<?php echo $dato->getId(); ?>/"><i class="fa fa-times"></i></a>
							</td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
			<a class="btn btn-primary" id="servicio" >Agregar Servicio</a>
		</form>

	  </div>
</div>

<?php } ?>

<div class="modal fade" id="modal-vacuna">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Agregar Vacuna</h4>
			</div>
			<div class="modal-body">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL.'mascota/agregarVacuna/' ?>" id="form-vacuna">
					<input type="hidden" name="mascota" value="<?php if(isset($this->dato)){ echo $this->dato->getId();} ?>">
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Vacuna: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<?php echo $this->combobox("vacuna", "Seleccione...", $this->vacunas, "", "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha Program: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<input name="fechaProg" value="" class="form-control fechadatepicker required" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" />
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Observacion: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<textarea class="form-control required" name="observacion"></textarea>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" class="btn btn-primary" id="guardarVacuna" >Guardar</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal-servicio">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Agregar Servicio</h4>
			</div>
			<div class="modal-body">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL.'mascota/agregarServicio/' ?>" id="form-servicio">
					<input type="hidden" name="mascota" value="<?php if(isset($this->dato)){ echo $this->dato->getId();} ?>">
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Servicio: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<?php echo $this->combobox("servicio", "Seleccione...", $this->servicios, "", "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha Program: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<input name="fechaProg" value="" class="form-control fechadatepicker required" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" />
						</div>
					</div>
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Observacion: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<textarea class="form-control required" name="observacion"></textarea>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" class="btn btn-primary" id="guardarServicio" >Guardar</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal-asignar-vacuna">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Fecha Vacuna</h4>
			</div>
			<div class="modal-body">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL.'mascota/asignarVacuna/' ?>" id="form-vacunaF">
					<input type="hidden" name="mascota" value="<?php if(isset($this->dato)){ echo $this->dato->getId();} ?>">
					<input type="hidden" name="vacuna" value="" id="id-vacuna" >
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<input name="fechaRealVacuna" value="" class="form-control fechadatepicker required" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" />
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" class="btn btn-primary" id="guardarVacunaF" >Guardar</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal-asignar-servicio">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Fecha Servicio</h4>
			</div>
			<div class="modal-body">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo BASE_URL.'mascota/asignarServicio/' ?>" id="form-servicioF">
					<input type="hidden" name="mascota" value="<?php if(isset($this->dato)){ echo $this->dato->getId();} ?>">
					<input type="hidden" name="servicio" value="" id="id-servicio" >
					<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha: </label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<input name="fechaRealServicio" value="" class="form-control fechadatepicker required" data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" />
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="button" class="btn btn-primary" id="guardarServicioF" >Guardar</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('#vacuna').click(function(event) {
			$('#modal-vacuna').modal();
			$('#guardarVacuna').click(function(event) {
				$('#form-vacuna').submit();
			});		
		});
		$('#servicio').click(function(event) {
			$('#modal-servicio').modal();
			$('#guardarServicio').click(function(event) {
				$('#form-servicio').submit();
			});		
		});
		$(".asignarV").click(function(event) {
			$("#id-vacuna").val($(this).attr('vacuna'));
			$("#modal-asignar-vacuna").modal();
			$('#guardarVacunaF').click(function(event) {
				$('#form-vacunaF').submit();
			});
		});
		$(".asignarS").click(function(event) {
			$("#id-servicio").val($(this).attr('servicio'));
			$("#modal-asignar-servicio").modal();
			$('#guardarServicioF').click(function(event) {
				$('#form-servicioF').submit();
			});
		});
	});
</script>