<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title"><?php echo ucwords(strtolower($this->_presentRequest->getMetodo())); ?></h3>
	  </div>
	  <div class="panel-body">

	    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">

	    	<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Codigo: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="codigo" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getCodigoBppim();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Nombre: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="nombre" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getNombre();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Proponente: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input name="proponente" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getProponente();} ?>" />
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Categoria: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
				<?php $categoria = ''; ?>
				<?php if(isset($this->dato)){ $categoria = $this->dato->getCategoria()->getId(); } ?>
					<?php echo $this->combobox("categoria", "Seleccione...", $this->categorias, $categoria, "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Sector: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
				<?php $sector = ''; ?>
				<?php if(isset($this->dato)){ $sector = $this->dato->getSector()->getId(); } ?>
					<?php echo $this->combobox("sector", "Seleccione...", $this->sectores, $sector, "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Estado: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
				<?php $estado = ''; ?>
				<?php if(isset($this->dato)){ $estado = $this->dato->getEstado()->getId(); } ?>
					<?php echo $this->combobox("estado", "Seleccione...", $this->estados, $estado, "getId", "getDescripcion", "class='form-control required show-tick' data-live-search='true' ","getDescripcion"); ?>
				</div>
			</div>

			<p class="text-right comentario">
				Los campos marcados con <span class="span">*</span> son obligatorios.
			</p>

			<button type="submit" class="btn btn-primary" ><?php echo ucwords($this->_presentRequest->getMetodo()); ?> </button> 
			<a class="btn btn-primary" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>">Listado</a>

		</form>

	  </div>
</div>