<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title">Listado</h3>
	  </div>
	  <div class="panel-body">
	  <form role="form" method="post" enctype="multipart/form-data">
	  	<input type="hidden" name="guardar" value="1">
			<table class="table table-striped table-bordered table-hover" id="dataTablesAdvanced">
				<thead>
					<tr>
						<th>Requisitos de Viabilizacion</th>
						<th class="text-center" style="width:60px">SI</th>
						<th class="text-center" style="width:60px">NO</th>
						<th class="text-center" style="width:60px">N/A</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->datos as $key => $dato) { ?>
						<tr>
							<td><input type="hidden" name="r<?php echo $dato->getRequerimiento()->getId() ?>" value="<?php echo $dato->getRequerimiento()->getId() ?>"><?php echo $dato->getRequerimiento()->getDescripcion(); ?></td>
							<td class="text-center"><input type="radio" <?php if($dato->getEstado() == 1) echo "checked" ?> name="op<?php echo $dato->getRequerimiento()->getId() ?>" value="1" ></td>
							<td class="text-center"><input type="radio" <?php if($dato->getEstado() == 2) echo "checked" ?> name="op<?php echo $dato->getRequerimiento()->getId() ?>" value="2" ></td>
							<td class="text-center"><input type="radio" <?php if($dato->getEstado() == 0) echo "checked" ?> name="op<?php echo $dato->getRequerimiento()->getId() ?>" value="0" ></td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
			<button type="submit" class="btn btn-primary" >Guardar</button> 
		</form>
	  </div>
</div>
