<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proyecto extends \Entities\Proyecto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'numRadicado', 'codigobppim', 'nombre', 'proponente', 'fechacreacion', 'valor', 'numbeneficiario', 'justificacion', 'dimension', 'vigencia', 'meses', 'fecharadicacion', 'observacion', 'categoria', 'estado', 'sector', 'asignaciones');
        }

        return array('__isInitialized__', 'id', 'numRadicado', 'codigobppim', 'nombre', 'proponente', 'fechacreacion', 'valor', 'numbeneficiario', 'justificacion', 'dimension', 'vigencia', 'meses', 'fecharadicacion', 'observacion', 'categoria', 'estado', 'sector', 'asignaciones');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proyecto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumRadicado($numRadicado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumRadicado', array($numRadicado));

        return parent::setNumRadicado($numRadicado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumRadicado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumRadicado', array());

        return parent::getNumRadicado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigobppim($codigobppim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigobppim', array($codigobppim));

        return parent::setCodigobppim($codigobppim);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigobppim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigobppim', array());

        return parent::getCodigobppim();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setProponente($proponente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProponente', array($proponente));

        return parent::setProponente($proponente);
    }

    /**
     * {@inheritDoc}
     */
    public function getProponente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProponente', array());

        return parent::getProponente();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacreacion($fechacreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacreacion', array($fechacreacion));

        return parent::setFechacreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacreacion', array());

        return parent::getFechacreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', array($valor));

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', array());

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumbeneficiario($numbeneficiario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumbeneficiario', array($numbeneficiario));

        return parent::setNumbeneficiario($numbeneficiario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumbeneficiario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumbeneficiario', array());

        return parent::getNumbeneficiario();
    }

    /**
     * {@inheritDoc}
     */
    public function setJustificacion($justificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJustificacion', array($justificacion));

        return parent::setJustificacion($justificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getJustificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJustificacion', array());

        return parent::getJustificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDimension($dimension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDimension', array($dimension));

        return parent::setDimension($dimension);
    }

    /**
     * {@inheritDoc}
     */
    public function getDimension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDimension', array());

        return parent::getDimension();
    }

    /**
     * {@inheritDoc}
     */
    public function setVigencia($vigencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVigencia', array($vigencia));

        return parent::setVigencia($vigencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getVigencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVigencia', array());

        return parent::getVigencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeses($meses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeses', array($meses));

        return parent::setMeses($meses);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeses', array());

        return parent::getMeses();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharadicacion($fecharadicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharadicacion', array($fecharadicacion));

        return parent::setFecharadicacion($fecharadicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharadicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharadicacion', array());

        return parent::getFecharadicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria($categoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($categoria));

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', array());

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setSector($sector = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', array($sector));

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function getSector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', array());

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignaciones', array());

        return parent::getAsignaciones();
    }

}
