<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title">Listado</h3>
	  </div>
	  <div class="panel-body">
				<table class="table table-striped table-bordered table-hover" id="dataTablesAdvanced">
					<thead>
						<tr>
							<th>Cedula</th>
							<th>Nombre</th>
							<th>Cargo</th>
							<th>Entidad</th>
							<th>Estado</th>
							<th class="text-center no-sort" >Acción</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->datos as $key => $dato) { ?>
							<tr>
								<td><?php echo $dato->getCedula(); ?></td>
								<td><?php echo $dato->getNombre(); ?></td>
								<td><?php echo $dato->getCargo(); ?></td>
								<td><?php echo $dato->getEntidad()->getNombre(); ?></td>
								<td><?php echo $dato->getEstado()?'ACTIVO':'INACTIVO'; ?></td>
								<td class="text-center">
									<a title="Actualizar" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>actualizar/<?php echo $dato->getId(); ?>/"><i class="fa fa-pencil-square-o"></i></a>
								</td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
				<a href="<?php echo BASE_URL.$this->_presentRequest->getControlador()."/agregar/" ?>" class="btn btn-primary">Agregar</a>
	  </div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('.this-vermas').click(function(event) {
	        event.preventDefault();
	        motrarGet($(this),BASE.url+'<?php echo $this->_presentRequest->getControlador(); ?>/get/');
	    });
	});
</script>