<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title"><?php echo ucwords(strtolower($this->_presentRequest->getMetodo())); ?></h3>
	  </div>
	  <div class="panel-body">

	    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">

		    <div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Cedula: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input class="form-control required" name="cedula" value="<?php if(isset($this->dato)){ echo $this->dato->getCedula();} ?>">
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Nombre: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input class="form-control required" name="nombre" value="<?php if(isset($this->dato)){ echo $this->dato->getNombre();} ?>">
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Cargo: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<input class="form-control" name="cargo" required value="<?php if(isset($this->dato)){ echo $this->dato->getCargo();} ?>">
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Entidad: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
				<?php $entidad = ''; ?>
				<?php if(isset($this->dato)){ $entidad = $this->dato->getEntidad()->getId(); } ?>
					<?php echo $this->combobox("entidad", "Seleccione...", $this->entidades, $entidad, "getId", "getNombre", "class='form-control show-tick' data-live-search='true' ","getNombre"); ?>
				</div>
			</div>

			<div class="form-group">
				<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Estado: </label>
				<div class="col-xs-12 col-sm-9 col-lg-9">
					<div class="btn-group" data-toggle="buttons">
						<label class="btn btn-primary <?php if(isset($this->dato) && $this->dato->getEstado()){ echo 'active';}else if(!isset($this->dato)){ echo 'active'; } ?>">
							<input type="radio" name="estado" value="1" autocomplete="off" <?php if(isset($this->dato) && $this->dato->getEstado()){ echo 'checked';}else if(!isset($this->dato)){ echo 'checked'; } ?>> Activo
						</label>
						<label class="btn btn-primary <?php if(isset($this->dato) && !$this->dato->getEstado()){ echo 'active';} ?>">
							<input type="radio" name="estado" value="0" autocomplete="off" <?php if(isset($this->dato) && !$this->dato->getEstado()){ echo 'checked';} ?>> Inactivo 
						</label>
					</div>
				</div>
			</div>

			<p class="text-right comentario">
				Los campos marcados con <span class="span">*</span> son obligatorios.
			</p>

			<button type="submit" class="btn btn-primary" ><?php echo ucwords($this->_presentRequest->getMetodo()); ?> </button> 
			<a class="btn btn-primary" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>">Listado</a>

		</form>

	  </div>
</div>

